import type { Metadata } from "next";
import { Afacad_Flux, Nunito } from "next/font/google";
import "./globals.css";
import {StarfieldBackground} from "@/components/ui/starfield";
import Navbar from "@/components/Navbar";

const afacadFlux = Afacad_Flux({
  variable: "--font-afacad-flux",
  subsets: ["latin"],
    weight:'600',
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: "600",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${afacadFlux.variable} antialiased`}
      >
      <StarfieldBackground/>
      <Navbar/>
        {children}
      </body>
    </html>
  );
}
